# Generated by Django 4.2.3 on 2023-08-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentView',
        ),
    ]
