# Generated by Django 4.2.3 on 2023-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус платежа'),
        ),
    ]
