# Generated by Django 4.2.3 on 2023-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscription_options_paymentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата старта подписки'),
        ),
    ]
