# Generated by Django 4.2.3 on 2023-08-11 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
