version: '3'

services:
  web:
    restart: unless-stopped
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    env_file:
      - .env.docker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - pgdb

  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:7-alpine

  worker:
    restart: unless-stopped
    container_name: celery_worker
    build: .
    command: celery -A djangoWeather worker --pool=solo -l info
    env_file:
      - .env.docker
    depends_on:
      - web
      - redis

  pgdb:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: pgdb
    hostname: pgdb
    env_file:
      - ./.env.docker
    volumes:
      - pgdb:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  pgdb: