# Generated by Django 4.2.3 on 2023-07-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Название города'),
        ),
    ]
